version: "3"
services:

    # App
    systemeio-test-app:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        container_name: systemeio-test-app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - systemeio-test-db
        networks:
            - app_network

    # Web Server
    systemeio-test-webserver:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        container_name: systemeio-test-webserver
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - .:/var/www
        depends_on:
            - systemeio-test-app
        networks:
            - app_network

    # Data Base
    systemeio-test-db:
        image: postgres:alpine
        container_name: systemeio-test-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASS}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - 5432:5432
        volumes:
            - db_volume:/var/lib/postgresql
        networks:
            - app_network

# Docker Volumes
volumes:
    db_volume:
        driver: local

# Docker Networks
networks:
    app_network:
        driver: bridge

